POST http://localhost:3000/recipes/insertRecipe/Estados%20Unidos HTTP/1.1
content-type: application/json

{
    "nombre": "Buffalo wings",
    "descripcion":[
        "Cuando viajé a Estados Unidos, terminé de descubrir que la cocina del país corresponde a una gran mezcla de gastronomías nacionales como la europea, la asiática y la africana. Es así que podéis encontrar desde la famosa comida “fast food” como la hamburguesa o las papas fritas hasta productos como el pavo, maíz, habas, girasol, pimientos o patatas.",
        "Pues si andáis con ganas de preparar un de los platos típicos de Estados Unidos, de seguro que las Buffalo wings o alitas de pollo os encantará. También denominada como hot wings o chicken wings, esta exquisita preparación consta de alitas de pollo fritas que suelen bañarse en salsas especiales, como la de estilo búfalo, hecha con salsa picante de vinagre y cayena junto con margarina o mantequilla.",
        "En tanto sus características, por lo general las Buffalo wings se deben secar para que logren escurrir todo el aceite y de esta manera, quedar crujientes. Asimismo, como principal acompañamiento de este plato de Estados Unidos podéis servir apio cortado y un poquito de salsa de queso azul (llamado también queso roquefort)."
    ],
    "imagen": "https://recetasdeviajes.com/wp-content/uploads/2011/05/r173.jpg",
    "ingredientes": [
        {
            "nombre": "alitas de pollo limpias",
            "cantidad": "1 kilo",
            "opcional": false
        },
        {
            "nombre": "mantequilla sin sal",
            "cantidad": "1 barra",
            "opcional": false
        },
        {
            "nombre": "dientes de ajo picados",
            "cantidad": "2",
            "opcional": false
        },
        {
            "nombre": "pasta de tomate",
            "cantidad": "2 cucharadas",
            "opcional": false
        },
        {
            "nombre": "vinagre blanco",
            "cantidad": "2 cucharadas",
            "opcional": false
        },
        {
            "nombre": "consomé de pollo en polvo",
            "cantidad": "2 cucharadas",
            "opcional": false
        },
        {
            "nombre": "vino blanco",
            "cantidad": "1/2 taza",
            "opcional": false
        },
        {
            "nombre": "salsa tabasco",
            "cantidad": "!/2 taza",
            "opcional": true
        }
    ],
    "preparacion": [
        "Lo primero que debéis realizar es tomar una sartén y llevarla a fuego suave. Derretir la mantequilla, añadir el ajo picado y comenzar a revolver con cuchara de madera hasta que observéis que modifica su color.",
        "A continuación, agregar el resto de los ingredientes (menos las alitas de pollo), el vino blanco y seguir revolviendo por 5 minutos más.",
        "Por otra parte, debéis adobar todas las alitas de pollo con sal y pimienta a gusto. Tomar una cacerola grande, incorporar bastante aceite y llevar todos los ejemplares a fritar (si no queréis fritarlas, podéis llevarlas a horno fuerte por 20 minutos aproximadamente).",
        "Bañar las alitas de pollo con la salsa tabasco una vez que esté todas fritas. Recuerden que deben dejar que se terminen de secar por completo para que queden bien crujientes.",
        "Como dato adicional, os comento que podéis acompañar con otra salsa como medio pote de mayonesa, ¼ de ketchup y ¼ de queso azul."
    ],
    "consejos":[]
}

###

POST http://localhost:3000/recipes/insertRecipe/Rusia HTTP/1.1
content-type: application/json

{
    "nombre": "Palmeni",
    "descripcion": ["Hoy te estamos acercando uno de los platos más deliciosos y típicos de la gastronomía rusa, el cual podéis preparar en tu cocina. Este tipo de cocina sabe combinar lo europeo con lo oriental, lo cual le da un valor agregado a cada ingrediente. Ahora bien, el tema central de día es cómo preparar los pelmeni. ¿Los conocéis?",
                    "Si nos referimos a su origen ruso, este plato se cree que vino de la zona de los Montes Urales, y posee gran similitud con los llamados en Komi «pelnyan», literalmente «orejas de pan».",
                    "Básicamente lo que vas a precisar para su elaboración es hacer una rica masa de pasta y un relleno compuesto de bolitas de carne de cerdo, aunque existen también otras opciones como los siberianos, de pescado, con rábanos y de setas.",
                    "A continuación, toma nota de la receta que hoy te pasamos para tu agenda de cocina. Ésta en concreto es para 4 comensales."],
    "imagen": "https://recetasdeviajes.com/wp-content/uploads/2010/06/pelmeni-de-rusia.jpg",
    "ingredientes": [
        {
            "nombre":"harina de trigo",
            "cantidad":"320 gramo",
            "opcional": false
        },
        {
            "nombre":"huevo",
            "cantidad":"1",
            "opcional": false
        },
        {
            "nombre":"agua",
            "cantidad":"200 ml",
            "opcional": false
        },
        {
            "nombre":"sal",
            "cantidad":"10 gramos",
            "opcional": false
        },
        {
            "nombre":"carne de cerdo",
            "cantidad":"450 gramoS",
            "opcional": false
        },
        {
            "nombre":"cebolla",
            "cantidad":"50 gramos",
            "opcional": false
        },
        {
            "nombre":"Pimienta",
            "cantidad":"a gusto",
            "opcional": false
        },
        {
            "nombre":"manteca",
            "cantidad":"75 gramos",
            "opcional": false
        },
        {
            "nombre":"vinagre",
            "cantidad":"25 gramos",
            "opcional": false
        },
        {
            "nombre":"nata agria",
            "cantidad":"100 gramos",
            "opcional": false
        },
        {
            "nombre":"Perejil",
            "cantidad":"a gusto",
            "opcional": false
        }
    ],
    "preparacion": ["Lo primero que debes hacer es tamizar la harina. Para ello debes pasarla por un colador. Una vez terminado este paso, toma un bol e introduce la harina, la leche o agua, sal y el huevo. Ahora si, amasa hasta conseguir una consistencia espesa. Tápala con un repasador durante media hora.",
                "Pasado el tiempo, debes cortar la masa en trozos y aplástala en capas bien finas. En una de sus mitades colocar el relleno que en breve te comentamos su elaboración.",
                "Envuelve en forma de media luna cada pelmeni y une los bordes con los dedos. Para hervirlos coloca agua con sal gruesa en una olla.",
                "Ya tienes la masa preparada. Ahora lo primero que debes hacer es limpiar la carne y cortarla en tiritas bien finas. Asimismo, no te olvides de picar la cebolla.",
                "En un sartén saltea la carne de cerdo junto con la cebolla y añades sal, pimienta, un chorrito de agua y continuas revolviendo hasta lograr la mezcla deseada.",
                "Ahora que tienes todo listo, dejas hervirlos durante 5 minutos y ya están para servir en la mesa. Un consejo, quedan riquísimos con mantequilla caliente, vinagre o nata agria."],
    "consejos": []
}